ARG IMAGE=debian
ARG TAG=bullseye-slim
FROM ${IMAGE}:${TAG}

WORKDIR /usr/src/app
EXPOSE 3000 8080

ARG USERNAME=perl
ARG USER_UID=1000
ARG USER_GID=1000


RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USERNAME --shell /bin/bash --create-home $USERNAME

RUN apt-get update && apt-get install -y --no-install-recommends \
  software-properties-common \
  dirmngr \
  cpanminus \
  curl \
  gcc \
  gnupg \
  vim \
  make \
  libcpanel-json-xs-perl  \
  libdbi-perl  \
  libev-perl  \
  libfuture-asyncawait-perl  \
  libio-socket-socks-perl  \
  libnet-ssleay-perl  \
  libio-socket-ssl-perl  \
  libnet-dns-native-perl  \
  librole-tiny-perl  \
  libsql-abstract-perl  \
  libpq-dev \
  && rm -r /var/lib/apt/lists/* 

ENV MOJO_VERSION 9.33
RUN cpanm DBD::Pg \
 && rm -r /root/.cpanm


RUN cpanm Mojolicious@"$MOJO_VERSION" \
  DBD::Pg Mojo::Pg \
 && rm -r /root/.cpanm

RUN apt-get install -y --no-install-recommends \
  libauthen-sasl-perl \
  libnet-ssh2-perl \
  libgd-dev \
  libgd-perl \
  libio-socket-ssl-perl \
  libemail-valid-perl \
  libexcel-writer-xlsx-perl \
  libemail-address-list-perl \
  libemail-mime-perl \
  libemail-valid-perl \
  libemail-sender-perl \
  libmail-imapclient-perl \
  libencode-hanextra-perl \
  libgeo-ip-perl \
  libdomain-publicsuffix-perl \
  libauthen-sasl-perl \
  libhtml-scrubber-perl \
  libdatetime-perl \
  libdatetime-format-pg-perl \
  libmojolicious-plugin-assetpack-perl \
  libmojolicious-plugin-authentication-perl  \
  libemail-sender-perl \
  libhttp-browserdetect-perl \
  libuniversal-require-perl \
  libnet-scp-expect-perl  \
  libcss-minifier-perl \
  libjavascript-minifier-perl \
  libgd-securityimage-perl   \
  libemail-address-list-perl \
  libcss-minifier-xs-perl \
  libmime-tools-perl \
  libclone-perl \
  graphicsmagick \
  graphicsmagick-imagemagick-compat \
  libgraphics-magick-perl \
  libcrypt-openssl-rsa-perl \
  && rm -r /var/lib/apt/lists/* 

RUN cpanm   \
  Mojolicious::Plugin::RemoteAddr \
  Module::Pluggable@5.2 \
  Email::Sender::Simple \
  Encode::Detect::Detector \
  Mojolicious::Plugin::Minion \
  WWW::Crawler::Mojo \
  Mojolicious::Plugin::Captcha  \
  Mojolicious::Plugin::Restify \
  Mojolicious::Plugin::Cron \
  Crypt::Mode::CBC \
  Algorithm::HowSimilar \
  CSS::Sass \
  Mojo::JWT::Google  \
  Authen::SASL  \
  && rm -r /root/.cpanm

  ARG NOW=not-set

CMD ["/bin/bash", "-c"]
