name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the APP Docker image
      run: docker build . --file agent --tag darrenli912/chat
    - name: Push image to docker hub
      run: |
        docker login -u ${{ secrets.DOCKER_ACCOUNT }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push darrenli912/chat
