name: GENERATE APP IMAGE

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the APP Docker image
      run: docker build . --file Dockerfile --tag darrenli912/gtt:9.38
    - name: Push image to docker hub
      run: |
        docker login -u ${{ secrets.DOCKER_ACCOUNT }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push darrenli912/gtt:9.38

